### ISSUE TITLE
Animation does not Work in Version (0.9.0)

### ISSUE THREAD

**Issue by uzairjalil2** [c-frame/aframe-extras#422]
I implemented this project with aframe version (0.5.0 to 0.8.0), then it was running successfully. But I have to use the aframe version greater than (0.9.0). When I implement this project in version of (0.9.0) it gives some error and does not load on new version of   #@aframe. 

**Errors:**

- three.js:38181 THREE.JSONLoader has been removed.

- core:a-node:error Failure loading node:   TypeError: loader.load is not a function
    at i.update (aframe-extras.js:22029:12)
    at i.initComponent (component.js:330:10)
    at i.updateProperties (component.js:302:12)
    at HTMLElement.value (a-entity.js:490:19)
    at HTMLElement.value (a-entity.js:463:14)
    at a-entity.js:249:14
    at a-node.js:127:21

**Comment by vincentfretin** [comment]
Like the message said JSONLoader was removed from threejs and the json-model component was removed from this repo a long time ago. It's really old, I couldn't find any reference that this existed. I just found out this really old repo that included an old aframe-extras build https://github.com/rexraptor08/animation-controls/tree/master/js that included it.
I see there is a object-model loader in this repo to load a JSON, is this something interesting to you?
You probably want to convert your json files to gltf and use gltf-model component.
